---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
data:
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_ENV_envName": "minikube-dev",
      };
    })();

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vuejs
  name: vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vuejs
    spec:
      containers:
        - image: vuejs-app:0.0.2
          name: vuejs-app
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
          imagePullPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: fe-config

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vuejs
  name: vuejs
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vuejs
